<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K7Y90qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k7Y_90q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k7Y_90q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'receival' => ['privates', '.errored..service_locator.k7Y_90q.App\\Entity\\Receival', NULL, 'Cannot autowire service ".service_locator.k7Y_90q": it references class "App\\Entity\\Receival" but no such service exists.'],
        ], [
            'em' => '?',
            'receival' => 'App\\Entity\\Receival',
        ]);
    }
}
