<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PwlzJ8fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PwlzJ8f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PwlzJ8f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'delivery' => ['privates', '.errored..service_locator.PwlzJ8f.App\\Entity\\Delivery', NULL, 'Cannot autowire service ".service_locator.PwlzJ8f": it references class "App\\Entity\\Delivery" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'delivery' => 'App\\Entity\\Delivery',
            'em' => '?',
        ]);
    }
}
