<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UJq2g_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u_Jq2g.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u_Jq2g.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'vehicle' => ['privates', '.errored..service_locator.u_Jq2g..App\\Entity\\Vehicle', NULL, 'Cannot autowire service ".service_locator.u_Jq2g.": it references class "App\\Entity\\Vehicle" but no such service exists.'],
        ], [
            'vehicle' => 'App\\Entity\\Vehicle',
        ]);
    }
}
