<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M6QfgUOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m6QfgUO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m6QfgUO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'deliveryorder' => ['privates', '.errored..service_locator.m6QfgUO.App\\Entity\\DeliveryOrder', NULL, 'Cannot autowire service ".service_locator.m6QfgUO": it references class "App\\Entity\\DeliveryOrder" but no such service exists.'],
        ], [
            'deliveryorder' => 'App\\Entity\\DeliveryOrder',
        ]);
    }
}
