<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3tVt3VSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3tVt3VS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3tVt3VS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'delivery' => ['privates', '.errored..service_locator.3tVt3VS.App\\Entity\\Delivery', NULL, 'Cannot autowire service ".service_locator.3tVt3VS": it references class "App\\Entity\\Delivery" but no such service exists.'],
        ], [
            'delivery' => 'App\\Entity\\Delivery',
        ]);
    }
}
