<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UfeBwknService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ufeBwkn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ufeBwkn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'stockage' => ['privates', '.errored..service_locator.ufeBwkn.App\\Entity\\Stockage', NULL, 'Cannot autowire service ".service_locator.ufeBwkn": it references class "App\\Entity\\Stockage" but no such service exists.'],
        ], [
            'em' => '?',
            'stockage' => 'App\\Entity\\Stockage',
        ]);
    }
}
