<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GXZ_JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._G_XZ.j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._G_XZ.j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'stockageRepository' => ['privates', 'App\\Repository\\StockageRepository', 'getStockageRepositoryService', true],
        ], [
            'stockageRepository' => 'App\\Repository\\StockageRepository',
        ]);
    }
}
