<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeliveryOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.evitApK.App\Entity\DeliveryOrder' shared service.
     *
     * @return \App\Entity\DeliveryOrder
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.evitApK": it references class "App\\Entity\\DeliveryOrder" but no such service exists.');
    }
}
