<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDelivery2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PwlzJ8f.App\Entity\Delivery' shared service.
     *
     * @return \App\Entity\Delivery
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.PwlzJ8f": it references class "App\\Entity\\Delivery" but no such service exists.');
    }
}
