<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReceivalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VGWEgaP.App\Entity\Receival' shared service.
     *
     * @return \App\Entity\Receival
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VGWEgaP": it references class "App\\Entity\\Receival" but no such service exists.');
    }
}
