<?php

namespace ContainerXtV3UjC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplier2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LDdqx0d.App\Entity\Supplier' shared service.
     *
     * @return \App\Entity\Supplier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LDdqx0d": it references class "App\\Entity\\Supplier" but no such service exists.');
    }
}
