<?php

namespace Container6LKVHs3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ceu7NjgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ceu7Njg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ceu7Njg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'supplierRepository' => ['privates', 'App\\Repository\\SupplierRepository', 'getSupplierRepositoryService', true],
        ], [
            'supplierRepository' => 'App\\Repository\\SupplierRepository',
        ]);
    }
}
