<?php

namespace Container6LKVHs3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LDdqx0dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LDdqx0d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LDdqx0d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'supplier' => ['privates', '.errored..service_locator.LDdqx0d.App\\Entity\\Supplier', NULL, 'Cannot autowire service ".service_locator.LDdqx0d": it references class "App\\Entity\\Supplier" but no such service exists.'],
        ], [
            'supplier' => 'App\\Entity\\Supplier',
        ]);
    }
}
