<?php

namespace Container6LKVHs3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EvitApKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.evitApK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.evitApK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'deliveryorder' => ['privates', '.errored..service_locator.evitApK.App\\Entity\\DeliveryOrder', NULL, 'Cannot autowire service ".service_locator.evitApK": it references class "App\\Entity\\DeliveryOrder" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'deliveryorder' => 'App\\Entity\\DeliveryOrder',
            'em' => '?',
        ]);
    }
}
