<?php

namespace Container6LKVHs3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KT5Bgf5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KT5Bgf5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KT5Bgf5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'deliveryorderRepository' => ['privates', 'App\\Repository\\DeliveryOrderRepository', 'getDeliveryOrderRepositoryService', true],
        ], [
            'deliveryorderRepository' => 'App\\Repository\\DeliveryOrderRepository',
        ]);
    }
}
