<?php

namespace Container6LKVHs3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BIxrfitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BIxrfit' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BIxrfit'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'inventory' => ['privates', '.errored..service_locator.BIxrfit.App\\Entity\\Inventory', NULL, 'Cannot autowire service ".service_locator.BIxrfit": it references class "App\\Entity\\Inventory" but no such service exists.'],
        ], [
            'inventory' => 'App\\Entity\\Inventory',
        ]);
    }
}
