<?php

namespace Container6LKVHs3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KlXCA0HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.klXCA0H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.klXCA0H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'inventory' => ['privates', '.errored..service_locator.klXCA0H.App\\Entity\\Inventory', NULL, 'Cannot autowire service ".service_locator.klXCA0H": it references class "App\\Entity\\Inventory" but no such service exists.'],
        ], [
            'em' => '?',
            'inventory' => 'App\\Entity\\Inventory',
        ]);
    }
}
