<?php

namespace Container6LKVHs3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClient2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.f2G_tRu.App\Entity\Client' shared service.
     *
     * @return \App\Entity\Client
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.f2G_tRu": it references class "App\\Entity\\Client" but no such service exists.');
    }
}
