<?php

namespace Container6LKVHs3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInventory2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.klXCA0H.App\Entity\Inventory' shared service.
     *
     * @return \App\Entity\Inventory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.klXCA0H": it references class "App\\Entity\\Inventory" but no such service exists.');
    }
}
