<?php

namespace Container6LKVHs3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVehicleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.M20MmEj.App\Entity\Vehicle' shared service.
     *
     * @return \App\Entity\Vehicle
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.M20MmEj": it references class "App\\Entity\\Vehicle" but no such service exists.');
    }
}
